name: riverpod_messages
description: A message notification listener for riverpod architecture
version: 1.0.1
homepage: https://www.quantos.it
repository: https://github.com/ftognetto/riverpod_messages

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter: null
